// <auto-generated />
using System;
using LocalizationInDatabase.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalizationInDatabase.Mvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LocalizationInDatabase.Mvc.Models.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LocalizationInDatabase.Mvc.Models.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Culture = "tr-TR"
                        },
                        new
                        {
                            Id = 2,
                            Culture = "en-US"
                        });
                });

            modelBuilder.Entity("LocalizationInDatabase.Mvc.Models.Entities.StringResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("StringResources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Navbar.Home.Index.Link",
                            Value = "Ana Sayfa"
                        },
                        new
                        {
                            Id = 2,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Navbar.Employees.List.Link",
                            Value = "Çalışanlar"
                        },
                        new
                        {
                            Id = 3,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Navbar.Languages.List.Link",
                            Value = "Diller"
                        },
                        new
                        {
                            Id = 4,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Submenu.Employees.Create.Button",
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 5,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Submenu.Employees.List.Button",
                            Value = "Listeye Dön"
                        },
                        new
                        {
                            Id = 6,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Submenu.Employees.Edit.Button",
                            Value = "Düzenle"
                        },
                        new
                        {
                            Id = 7,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Submenu.Employees.Delete.Button",
                            Value = "Sil"
                        },
                        new
                        {
                            Id = 8,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Submenu.Languages.Create.Button",
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 9,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Submenu.Languages.List.Button",
                            Value = "Listeye Dön"
                        },
                        new
                        {
                            Id = 10,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Submenu.Languages.Edit.Button",
                            Value = "Düzenle"
                        },
                        new
                        {
                            Id = 11,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Submenu.Languages.Delete.Button",
                            Value = "Sil"
                        },
                        new
                        {
                            Id = 12,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Submenu.StringResources.Create.Button",
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 13,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Submenu.StringResources.List.Button",
                            Value = "Listeye Dön"
                        },
                        new
                        {
                            Id = 14,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Submenu.StringResources.Edit.Button",
                            Value = "Düzenle"
                        },
                        new
                        {
                            Id = 15,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Submenu.StringResources.Delete.Button",
                            Value = "Sil"
                        },
                        new
                        {
                            Id = 16,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.Home.Index",
                            Value = "Ana Sayfa"
                        },
                        new
                        {
                            Id = 17,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.Employees.Create",
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 18,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.Employees.List",
                            Value = "Çalışanlar"
                        },
                        new
                        {
                            Id = 19,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.Employees.Details",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 20,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.Employees.Edit",
                            Value = "Düzenle"
                        },
                        new
                        {
                            Id = 21,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.Languages.Create",
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 22,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.Languages.List",
                            Value = "Diller"
                        },
                        new
                        {
                            Id = 23,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.Languages.Details",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 24,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.Languages.Edit",
                            Value = "Düzenle"
                        },
                        new
                        {
                            Id = 25,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.StringResources.Create",
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 26,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.StringResources.List",
                            Value = "Çeviriler"
                        },
                        new
                        {
                            Id = 27,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.StringResources.Details",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 28,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Breadcrumb.StringResources.Edit",
                            Value = "Düzenle"
                        },
                        new
                        {
                            Id = 29,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.List.Title",
                            Value = "Çalışanlar"
                        },
                        new
                        {
                            Id = 30,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.List.Heading",
                            Value = "Çalışanlar"
                        },
                        new
                        {
                            Id = 31,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.List.No_employees",
                            Value = "Çalışan yok."
                        },
                        new
                        {
                            Id = 32,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.List.Th_name",
                            Value = "ADI"
                        },
                        new
                        {
                            Id = 33,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.List.Details.Link",
                            Value = "İncele"
                        },
                        new
                        {
                            Id = 34,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.List.Edit.Link",
                            Value = "Düzenle"
                        },
                        new
                        {
                            Id = 35,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.List.Delete.Link",
                            Value = "Sil"
                        },
                        new
                        {
                            Id = 36,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Create.Title",
                            Value = "Çalışan Ekle"
                        },
                        new
                        {
                            Id = 37,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Create.Heading",
                            Value = "Çalışan Ekle"
                        },
                        new
                        {
                            Id = 38,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Create.Submit.Button",
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 39,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Create.Submit_and_return_list.Button",
                            Value = "Ekle ve Listeye Dön"
                        },
                        new
                        {
                            Id = 40,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Create.Return_list.Link",
                            Value = "Listeye Dön"
                        },
                        new
                        {
                            Id = 41,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Edit.Title",
                            Value = "Çalışanı Düzenle"
                        },
                        new
                        {
                            Id = 42,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Edit.Heading",
                            Value = "Çalışanı Düzenle"
                        },
                        new
                        {
                            Id = 43,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Edit.Submit.Button",
                            Value = "Kaydet"
                        },
                        new
                        {
                            Id = 44,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Edit.Submit_and_go_back.Button",
                            Value = "Kaydet ve Geri Dön"
                        },
                        new
                        {
                            Id = 45,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Edit.Go_back.Link",
                            Value = "Geri Dön"
                        },
                        new
                        {
                            Id = 46,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Edit.Submit_and_return_list.Button",
                            Value = "Kaydet ve Listeye Dön"
                        },
                        new
                        {
                            Id = 47,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Edit.Return_list.Link",
                            Value = "Listeye Dön"
                        },
                        new
                        {
                            Id = 48,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Details.Title",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 49,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Employees.Details.Heading",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 50,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.List.Title",
                            Value = "Diller"
                        },
                        new
                        {
                            Id = 51,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.List.Heading",
                            Value = "Diller"
                        },
                        new
                        {
                            Id = 52,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.List.No_languages",
                            Value = "Dil yok."
                        },
                        new
                        {
                            Id = 53,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.List.Th_culture",
                            Value = "KÜLTÜR KODU"
                        },
                        new
                        {
                            Id = 54,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.List.StringResources.Link",
                            Value = "Çeviriler"
                        },
                        new
                        {
                            Id = 55,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.List.Details.Link",
                            Value = "İncele"
                        },
                        new
                        {
                            Id = 56,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.List.Edit.Link",
                            Value = "Düzenle"
                        },
                        new
                        {
                            Id = 57,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.List.Delete.Link",
                            Value = "Sil"
                        },
                        new
                        {
                            Id = 58,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Create.Title",
                            Value = "Dil Ekle"
                        },
                        new
                        {
                            Id = 59,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Create.Heading",
                            Value = "Dil Ekle"
                        },
                        new
                        {
                            Id = 60,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Create.Submit.Button",
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 61,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Create.Submit_and_return_list.Button",
                            Value = "Ekle ve Listeye Dön"
                        },
                        new
                        {
                            Id = 62,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Create.Return_list.Link",
                            Value = "Listeye Dön"
                        },
                        new
                        {
                            Id = 63,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Details.Title",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 64,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Details.Heading",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 65,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Edit.Title",
                            Value = "Dili Düzenle"
                        },
                        new
                        {
                            Id = 66,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Edit.Heading",
                            Value = "Dili Düzenle"
                        },
                        new
                        {
                            Id = 67,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Edit.Submit.Button",
                            Value = "Kaydet"
                        },
                        new
                        {
                            Id = 68,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Edit.Submit_and_go_back.Button",
                            Value = "Kaydet ve Geri Dön"
                        },
                        new
                        {
                            Id = 69,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Edit.Go_back.Link",
                            Value = "Geri Dön"
                        },
                        new
                        {
                            Id = 70,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Edit.Submit_and_return_list.Button",
                            Value = "Kaydet ve Listeye Dön"
                        },
                        new
                        {
                            Id = 71,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.Edit.Return_list.Link",
                            Value = "Listeye Dön"
                        },
                        new
                        {
                            Id = 72,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.List.Title",
                            Value = "Çeviriler"
                        },
                        new
                        {
                            Id = 73,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.List.Heading",
                            Value = "Çeviriler"
                        },
                        new
                        {
                            Id = 74,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.List.No_resources",
                            Value = "Çeviri yok."
                        },
                        new
                        {
                            Id = 75,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.List.Th_name",
                            Value = "ADI"
                        },
                        new
                        {
                            Id = 76,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.List.Th_value",
                            Value = "ÇEVİRİ"
                        },
                        new
                        {
                            Id = 77,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.List.Th_is_approved",
                            Value = "DURUMU"
                        },
                        new
                        {
                            Id = 78,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.List.Approved",
                            Value = "Onaylı"
                        },
                        new
                        {
                            Id = 79,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.List.Unapproved",
                            Value = "Onaysız"
                        },
                        new
                        {
                            Id = 80,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.List.Details.Link",
                            Value = "İncele"
                        },
                        new
                        {
                            Id = 81,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.List.Edit.Link",
                            Value = "Düzenle"
                        },
                        new
                        {
                            Id = 82,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.List.Delete.Link",
                            Value = "Sil"
                        },
                        new
                        {
                            Id = 83,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Edit.Title",
                            Value = "Çeviriyi Düzenle"
                        },
                        new
                        {
                            Id = 84,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Edit.Heading",
                            Value = "Çeviriyi Düzenle"
                        },
                        new
                        {
                            Id = 85,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Edit.Submit.Button",
                            Value = "Kaydet"
                        },
                        new
                        {
                            Id = 86,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Edit.Submit_and_go_back.Button",
                            Value = "Kaydet ve Geri Dön"
                        },
                        new
                        {
                            Id = 87,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Edit.Go_back.Link",
                            Value = "Geri Dön"
                        },
                        new
                        {
                            Id = 88,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Edit.Submit_and_return_list.Button",
                            Value = "Kaydet ve Listeye Dön"
                        },
                        new
                        {
                            Id = 89,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Edit.Return_list.Link",
                            Value = "Listeye Dön"
                        },
                        new
                        {
                            Id = 90,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Details.Title",
                            Value = "Çeviri Detayları"
                        },
                        new
                        {
                            Id = 91,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Details.Heading",
                            Value = "Çeviri Detayları"
                        },
                        new
                        {
                            Id = 92,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Create.Title",
                            Value = "Çalışan Ekle"
                        },
                        new
                        {
                            Id = 93,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Create.Heading",
                            Value = "Çalışan Ekle"
                        },
                        new
                        {
                            Id = 94,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Create.Submit.Button",
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 95,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Create.Submit_and_return_list.Button",
                            Value = "Ekle ve Listeye Dön"
                        },
                        new
                        {
                            Id = 96,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "StringResources.Create.Return_list.Link",
                            Value = "Listeye Dön"
                        },
                        new
                        {
                            Id = 97,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Navbar.Home.Index.Link",
                            Value = "Home"
                        },
                        new
                        {
                            Id = 98,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Navbar.Employees.List.Link",
                            Value = "Employees"
                        },
                        new
                        {
                            Id = 99,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Navbar.Languages.List.Link",
                            Value = "Languages"
                        },
                        new
                        {
                            Id = 100,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.Employees.Create.Button",
                            Value = "Add New"
                        },
                        new
                        {
                            Id = 101,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.Employees.List.Button",
                            Value = "Back To List"
                        },
                        new
                        {
                            Id = 102,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.Employees.Edit.Button",
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 103,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.Employees.Delete.Button",
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 104,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.Employees.Details.Button",
                            Value = "Details"
                        },
                        new
                        {
                            Id = 105,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.Languages.Create.Button",
                            Value = "Add New"
                        },
                        new
                        {
                            Id = 106,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.Languages.List.Button",
                            Value = "Back To List"
                        },
                        new
                        {
                            Id = 107,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.Languages.Edit.Button",
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 108,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.Languages.Delete.Button",
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 109,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.StringResources.Create.Button",
                            Value = "Add New"
                        },
                        new
                        {
                            Id = 110,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.StringResources.List.Button",
                            Value = "Back To List"
                        },
                        new
                        {
                            Id = 111,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.StringResources.Edit.Button",
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 112,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Submenu.StringResources.Delete.Button",
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 113,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.Home.Index",
                            Value = "Home"
                        },
                        new
                        {
                            Id = 114,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.Employees.Create",
                            Value = "Add New"
                        },
                        new
                        {
                            Id = 115,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.Employees.List",
                            Value = "Employees"
                        },
                        new
                        {
                            Id = 116,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.Employees.Details",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 117,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.Employees.Edit",
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 118,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.Languages.Create",
                            Value = "Add New"
                        },
                        new
                        {
                            Id = 119,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.Languages.List",
                            Value = "Languages"
                        },
                        new
                        {
                            Id = 120,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.Languages.Details",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 121,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.Languages.Edit",
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 122,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.StringResources.Create",
                            Value = "Add New"
                        },
                        new
                        {
                            Id = 123,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.StringResources.List",
                            Value = "String Resources"
                        },
                        new
                        {
                            Id = 124,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.StringResources.Details",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 125,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Breadcrumb.StringResources.Edit",
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 126,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.List.Title",
                            Value = "Employees"
                        },
                        new
                        {
                            Id = 127,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.List.Heading",
                            Value = "Employees"
                        },
                        new
                        {
                            Id = 128,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.List.No_employees",
                            Value = "No employees."
                        },
                        new
                        {
                            Id = 129,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.List.Th_name",
                            Value = "NAME"
                        },
                        new
                        {
                            Id = 130,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.List.Details.Link",
                            Value = "Details"
                        },
                        new
                        {
                            Id = 131,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.List.Edit.Link",
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 132,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.List.Delete.Link",
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 133,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Create.Title",
                            Value = "New Employee"
                        },
                        new
                        {
                            Id = 134,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Create.Heading",
                            Value = "New Employee"
                        },
                        new
                        {
                            Id = 135,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Create.Submit.Button",
                            Value = "Save"
                        },
                        new
                        {
                            Id = 136,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Create.Submit_and_return_list.Button",
                            Value = "Save and Back To List"
                        },
                        new
                        {
                            Id = 137,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Create.Return_list.Link",
                            Value = "Back To List"
                        },
                        new
                        {
                            Id = 138,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Edit.Title",
                            Value = "Edit Employee"
                        },
                        new
                        {
                            Id = 139,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Edit.Heading",
                            Value = "Edit Employee"
                        },
                        new
                        {
                            Id = 140,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Edit.Submit.Button",
                            Value = "Save"
                        },
                        new
                        {
                            Id = 141,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Edit.Submit_and_go_back.Button",
                            Value = "Save and Go Back"
                        },
                        new
                        {
                            Id = 142,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Edit.Go_back.Link",
                            Value = "Go Back"
                        },
                        new
                        {
                            Id = 143,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Edit.Submit_and_return_list.Button",
                            Value = "Save and Back To List"
                        },
                        new
                        {
                            Id = 144,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Edit.Return_list.Link",
                            Value = "Back To List"
                        },
                        new
                        {
                            Id = 145,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Details.Title",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 146,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Employees.Details.Heading",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 147,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.List.Title",
                            Value = "Languages"
                        },
                        new
                        {
                            Id = 148,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.List.Heading",
                            Value = "Languages"
                        },
                        new
                        {
                            Id = 149,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.List.No_languages",
                            Value = "No languages."
                        },
                        new
                        {
                            Id = 150,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.List.Th_culture",
                            Value = "CULTURE"
                        },
                        new
                        {
                            Id = 151,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.List.StringResources.Link",
                            Value = "String Resources"
                        },
                        new
                        {
                            Id = 152,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.List.Details.Link",
                            Value = "Details"
                        },
                        new
                        {
                            Id = 153,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.List.Edit.Link",
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 154,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.List.Delete.Link",
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 155,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Create.Title",
                            Value = "New Language"
                        },
                        new
                        {
                            Id = 156,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Create.Heading",
                            Value = "New Language"
                        },
                        new
                        {
                            Id = 157,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Create.Submit.Button",
                            Value = "Save"
                        },
                        new
                        {
                            Id = 158,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Create.Submit_and_return_list.Button",
                            Value = "Save and Back To List"
                        },
                        new
                        {
                            Id = 159,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Create.Return_list.Link",
                            Value = "Back To List"
                        },
                        new
                        {
                            Id = 160,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Details.Title",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 161,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Details.Heading",
                            Value = "{0}"
                        },
                        new
                        {
                            Id = 162,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Edit.Title",
                            Value = "Edit Language"
                        },
                        new
                        {
                            Id = 163,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Edit.Heading",
                            Value = "Edit Language"
                        },
                        new
                        {
                            Id = 164,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Edit.Submit.Button",
                            Value = "Save"
                        },
                        new
                        {
                            Id = 165,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Edit.Submit_and_go_back.Button",
                            Value = "Save and Go Back"
                        },
                        new
                        {
                            Id = 166,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Edit.Go_back.Link",
                            Value = "Go Back"
                        },
                        new
                        {
                            Id = 167,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Edit.Submit_and_return_list.Button",
                            Value = "Save and Back To List"
                        },
                        new
                        {
                            Id = 168,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.Edit.Return_list.Link",
                            Value = "Back To List"
                        },
                        new
                        {
                            Id = 169,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.List.Title",
                            Value = "String Resources"
                        },
                        new
                        {
                            Id = 170,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.List.Heading",
                            Value = "String Resources"
                        },
                        new
                        {
                            Id = 171,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.List.No_resources",
                            Value = "No string resources."
                        },
                        new
                        {
                            Id = 172,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.List.Th_name",
                            Value = "NAME"
                        },
                        new
                        {
                            Id = 173,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.List.Th_value",
                            Value = "VALUE"
                        },
                        new
                        {
                            Id = 174,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.List.Th_is_approved",
                            Value = "STATUS"
                        },
                        new
                        {
                            Id = 175,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.List.Approved",
                            Value = "Approved"
                        },
                        new
                        {
                            Id = 176,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.List.Unapproved",
                            Value = "Unapproved"
                        },
                        new
                        {
                            Id = 177,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.List.Details.Link",
                            Value = "Details"
                        },
                        new
                        {
                            Id = 178,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.List.Edit.Link",
                            Value = "Edit"
                        },
                        new
                        {
                            Id = 179,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.List.Delete.Link",
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 180,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Edit.Title",
                            Value = "Edit String Resource"
                        },
                        new
                        {
                            Id = 181,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Edit.Heading",
                            Value = "Edit String Resource"
                        },
                        new
                        {
                            Id = 182,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Edit.Submit.Button",
                            Value = "Save"
                        },
                        new
                        {
                            Id = 183,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Edit.Submit_and_go_back.Button",
                            Value = "Save and Go Back"
                        },
                        new
                        {
                            Id = 184,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Edit.Go_back.Link",
                            Value = "Go Back"
                        },
                        new
                        {
                            Id = 185,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Edit.Submit_and_return_list.Button",
                            Value = "Save and Back To List"
                        },
                        new
                        {
                            Id = 186,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Edit.Return_list.Link",
                            Value = "Back To List"
                        },
                        new
                        {
                            Id = 187,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Details.Title",
                            Value = "Details"
                        },
                        new
                        {
                            Id = 188,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Details.Heading",
                            Value = "Details"
                        },
                        new
                        {
                            Id = 189,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Create.Title",
                            Value = "New String Resource"
                        },
                        new
                        {
                            Id = 190,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Create.Heading",
                            Value = "New String Resource"
                        },
                        new
                        {
                            Id = 191,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Create.Submit.Button",
                            Value = "Save"
                        },
                        new
                        {
                            Id = 192,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Create.Submit_and_return_list.Button",
                            Value = "Save and Back To List"
                        },
                        new
                        {
                            Id = 193,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "StringResources.Create.Return_list.Link",
                            Value = "Back To List"
                        },
                        new
                        {
                            Id = 194,
                            IsApproved = true,
                            LanguageId = 1,
                            Name = "Languages.List.Th_name",
                            Value = "ADI"
                        },
                        new
                        {
                            Id = 195,
                            IsApproved = true,
                            LanguageId = 2,
                            Name = "Languages.List.Th_name",
                            Value = "NAME"
                        });
                });

            modelBuilder.Entity("LocalizationInDatabase.Mvc.Models.Entities.StringResource", b =>
                {
                    b.HasOne("LocalizationInDatabase.Mvc.Models.Entities.Language", "Language")
                        .WithMany("StringResources")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("LocalizationInDatabase.Mvc.Models.Entities.Language", b =>
                {
                    b.Navigation("StringResources");
                });
#pragma warning restore 612, 618
        }
    }
}
